image:
  name: localhost:5000/microprofile-config
  tag: 1.0-SNAPSHOT
  # O chart não permite trocar o "imagePullPolicy"
  # https://github.com/wildfly/wildfly-charts/blob/bc17cb52b8999e2d95fbfb37f879b488c368a05d/charts/wildfly-common/templates/_deployment.yaml#L53
build:
  enabled: false
deploy:
  replicas: 1
  route:
    enabled: false 
