image:
  name: localhost:5000/microprofile-config
  tag: 1.0-SNAPSHOT
  # O chart não permite trocar o "imagePullPolicy"
  # https://github.com/wildfly/wildfly-charts/blob/bc17cb52b8999e2d95fbfb37f879b488c368a05d/charts/wildfly-common/templates/_deployment.yaml#L53
build:
  enabled: false
deploy:
  enabled: true
  replicas: 1
  route:
    enabled: false
  env:
  - name: CONFIG_PROP
    value: MyPropertyFileConfigValue-FOR-Helm
  - name: POSTGRESQL_USER
    value: db_user
  - name: POSTGRESQL_PASSWORD
    value: db_pass
  - name: POSTGRESQL_SERVICE_HOST
    value: postgres
  - name: POSTGRESQL_SERVICE_PORT
    value: '5432'
  - name: POSTGRESQL_DATABASE
    value: db_sample
  - name: POSTGRESQL_BACKGROUND_VALIDATION
    value: "true"
  - name: POSTGRESQL_BACKGROUND_VALIDATION_MILLIS
    value: "10000"
  - name: POSTGRESQL_VALIDATE_ON_MATCH
    value: "false"
  - name: POSTGRESQL_IDLE_TIMEOUT_MINUTES
    value: "10000"
  - name: POSTGRESQL_MAX_POOL_SIZE
    value: "5"
  - name: POSTGRESQL_MIN_POOL_SIZE
    value: "0"
  resources:
    requests: # solicitado
      cpu: 100m
      memory: "64Mi"
    limits:  # limite máximo
      cpu: 500m
      memory: "400Mi"

